### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by AkhilaG28** [abhi-swami/civil-kettle-7397#48]
Presentation:

Very good presentation overall, good team work
Project:
Home page UI was good
Functiona;ity of app is good
login functionality and UI is good
Filtering part was good
I am not able to go to products when clicking on Navbar, only search working
checkout page and individual page is good
Overall very good project
Admin functionality is good
Github:

Documentation was minimal

**Comment by agrawalrajat310** [comment]
Thank you @AkhilaG28 for your supportive feedback ✨👋
